### PR TITLE
BasicClass Creation

### PR DESCRIPTION
**Pull request by majdew**
In this branch,  I created the basic class to handle with the data from the GUI application (number of typed characters,number of errors ,number of words per minute and list of errors) added some methods for create object set and get the data and compare method "to compare user typed character with original character"

### CODE REVIEW

**Comment by majdew** [comment]
[Creating the Basic Class named "BasicClass".](https://trello.com/c/NzDPBh36/2-creating-the-basic-class-named-basicclass)

**Comment by majdew** [comment]
[Creating the Basic Class named "BasicClass".](https://trello.com/c/NzDPBh36/2-creating-the-basic-class-named-basicclass)

**Review by none-none-56 — COMMENTED** [review]
Well Done @majdew 👍

**Comment by none-none-56** [comment]
[Editing BasicMenuForm](https://trello.com/c/e3AXkDfM/15-editing-basicmenuform)

**Pull request merged**
