### PR TITLE
GUI Design

### PR DESCRIPTION
**Pull request by none-none-56**
This branch contains the basic design of the GUI

### CODE REVIEW

**Comment by none-none-56** [comment]
[Design GUI application](https://trello.com/c/z3w8vmjn/4-design-gui-application)

**Comment by majdew** [comment]
In the practice menu you should add a label  without any text to set the text "Error" if there is an error in the typing characters

**Comment by none-none-56** [comment]
> In the practice menu you should add a label without any text to set the text "Error" if there is an error in the typing characters

**Comment by none-none-56** [comment]
Oh that's true .. thanks for noticing me :)

**Comment by none-none-56** [comment]
Done !

**Pull request merged**
